steps:
- name: node:10.15.1
  entrypoint: npm
  args: ["install"]
  dir: 'backend'
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "create-env"]
  dir: 'backend'
  env:
    - 'PUBSUB_TOKEN=${_PUBSUB_TOKEN}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy",  "--appyaml", "./app_pub.yaml"]
  dir: 'backend'
availableSecrets:
  secretManager:
  - versionName: projects/github-298920/secrets/PUBSUB_TOKEN/versions/1
    env: 'PUBSUB_TOKEN'