service: default
runtime: python311
entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker src.main:app

#smallest instance class
instance_class: F2

#prevents creating additional instances
automatic_scaling:
  min_instances: 1
  max_instances: 16

env_variables:
  PROD: true
