service: default
runtime: python311
entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker src.main:app --timeout 600 --graceful-timeout 600

#smallest instance class
instance_class: F4

#prevents creating additional instances
automatic_scaling:
  min_instances: 0
  max_instances: 4

env_variables:
  PROD: true
