name: Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with unittest
      run: |
        cd backend
        coverage run --branch -m unittest
      env:
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    - name: Run coverage report
      run: |
        cd backend
        coverage report -m > tests/coverage/report.txt
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./backend/tests/coverage/
